#!/usr/bin/env node
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const DEFAULT_CONFIG_DIR = '/etc/kinglive/restreams';
const DEFAULT_STATE_FILE = '/var/lib/kinglive-restream-sync/state.json';
const DEFAULT_SYSTEMD_PREFIX = 'kinglive-restream@';
const DEFAULT_RTMP_BASE_URL = 'rtmp://127.0.0.1:1935/live';

async function main() {
  const options = parseArgs(process.argv.slice(2), process.env);
  if (!options.apiUrl) throw new Error('RESTREAM_API_URL is required');
  if (!options.token) throw new Error('RESTREAM_SYNC_TOKEN is required');

  const desired = await fetchDesiredRestreams(options);
  const state = await readJsonFile(options.stateFile, { managed: {} });
  const actions = await applyDesiredState(desired, state, options);
  await writeJsonFile(options.stateFile, state);

  for (const action of actions) {
    console.log(action);
  }
}

export async function applyDesiredState(restreams, state, options) {
  const desired = new Map();
  const actions = [];
  state.managed ||= {};

  for (const restream of restreams) {
    const item = normalizeRestream(restream, options);
    if (!item) continue;
    desired.set(item.slug, item);
    await writeEnvFile(item, options);

    const current = state.managed[item.slug] || {};
    const restartChanged = item.restartRequestedAt && item.restartRequestedAt !== current.restartRequestedAt;
    const unit = `${options.systemdPrefix}${item.slug}.service`;

    if (item.desiredState === 'stopped' || item.isActive === false) {
      await systemctl(['disable', '--now', unit], options);
      actions.push(`stopped ${item.slug}`);
    } else if (!current.slug) {
      await systemctl(['enable', '--now', unit], options);
      actions.push(`started ${item.slug}`);
    } else if (restartChanged || configChanged(item, current)) {
      await systemctl(['restart', unit], options);
      actions.push(`restarted ${item.slug}`);
    } else {
      actions.push(`kept ${item.slug}`);
    }

    state.managed[item.slug] = {
      slug: item.slug,
      matchId: item.matchId,
      desiredState: item.desiredState,
      isActive: item.isActive,
      donorHash: item.donorHash,
      outputUrl: item.outputUrl,
      restartRequestedAt: item.restartRequestedAt,
      updatedAt: new Date().toISOString(),
    };
  }

  for (const slug of Object.keys(state.managed)) {
    if (desired.has(slug)) continue;
    const unit = `${options.systemdPrefix}${slug}.service`;
    await systemctl(['disable', '--now', unit], options);
    actions.push(`removed ${slug}`);
    delete state.managed[slug];
  }

  return actions;
}

export function normalizeRestream(restream, options) {
  const slug = normalizeSlug(restream?.slug || restream?.id);
  const donorUrl = String(restream?.donor_url || '').trim();
  const matchId = Number(restream?.match_id);
  if (!slug || !isHttpUrl(donorUrl) || !Number.isFinite(matchId) || matchId <= 0) return null;

  const desiredState = String(restream?.desired_state || 'running').toLowerCase() === 'stopped' ? 'stopped' : 'running';
  const outputUrl = String(restream?.output_url || `${options.publicBaseUrl}/${slug}/index.m3u8`).trim();
  return {
    slug,
    matchId,
    donorUrl,
    donorHash: hashText(donorUrl),
    outputUrl,
    rtmpUrl: `${options.rtmpBaseUrl.replace(/\/+$/, '')}/${slug}`,
    label: String(restream?.label || slug).trim(),
    desiredState,
    isActive: restream?.is_active !== false,
    restartRequestedAt: String(restream?.restart_requested_at || ''),
  };
}

export function renderEnvFile(item) {
  return [
    '# Generated by kinglive restream sync. Edit the admin panel instead.',
    `RESTREAM_SLUG=${shellQuote(item.slug)}`,
    `RESTREAM_LABEL=${shellQuote(item.label)}`,
    `RESTREAM_MATCH_ID=${shellQuote(String(item.matchId))}`,
    `RESTREAM_INPUT_URL=${shellQuote(item.donorUrl)}`,
    `RESTREAM_RTMP_URL=${shellQuote(item.rtmpUrl)}`,
    `RESTREAM_PUBLIC_URL=${shellQuote(item.outputUrl)}`,
    '',
  ].join('\n');
}

async function fetchDesiredRestreams(options) {
  const response = await fetch(options.apiUrl, {
    headers: {
      Accept: 'application/json',
      Authorization: `Bearer ${options.token}`,
    },
  });
  if (!response.ok) {
    throw new Error(`restream API failed: ${response.status}`);
  }
  const payload = await response.json();
  return Array.isArray(payload?.restreams) ? payload.restreams : [];
}

async function writeEnvFile(item, options) {
  const path = join(options.configDir, `${item.slug}.env`);
  const next = renderEnvFile(item);
  let current = '';
  try {
    current = await readFile(path, 'utf8');
  } catch {}
  if (current === next) return;
  if (options.dryRun) return;
  await mkdir(dirname(path), { recursive: true, mode: 0o750 });
  const tmp = `${path}.tmp-${process.pid}`;
  await writeFile(tmp, next, { mode: 0o640 });
  await rename(tmp, path);
}

async function systemctl(args, options) {
  if (options.dryRun) return;
  if (options.noSystemd) return;
  await execFile(options.systemctlBin, args);
}

async function execFile(command, args) {
  await new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
    });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${command} ${args.join(' ')} failed: ${stderr.trim()}`));
    });
  });
}

async function readJsonFile(path, fallback) {
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch {
    return fallback;
  }
}

async function writeJsonFile(path, value) {
  await mkdir(dirname(path), { recursive: true, mode: 0o750 });
  const tmp = `${path}.tmp-${process.pid}`;
  await writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o640 });
  await rename(tmp, path);
}

function parseArgs(args, env) {
  const values = new Map();
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (!arg.startsWith('--')) continue;
    const key = arg.slice(2);
    const next = args[index + 1];
    if (next && !next.startsWith('--')) {
      values.set(key, next);
      index += 1;
    } else {
      values.set(key, 'true');
    }
  }

  const apiUrl = values.get('api-url') || env.RESTREAM_API_URL || '';
  const publicBaseUrl = values.get('public-base-url') || env.RESTREAM_PUBLIC_BASE_URL || inferPublicBaseUrl(apiUrl);
  return {
    apiUrl,
    token: values.get('token') || env.RESTREAM_SYNC_TOKEN || '',
    configDir: values.get('config-dir') || env.RESTREAM_CONFIG_DIR || DEFAULT_CONFIG_DIR,
    stateFile: values.get('state-file') || env.RESTREAM_STATE_FILE || DEFAULT_STATE_FILE,
    systemdPrefix: values.get('systemd-prefix') || env.RESTREAM_SYSTEMD_PREFIX || DEFAULT_SYSTEMD_PREFIX,
    rtmpBaseUrl: values.get('rtmp-base-url') || env.RESTREAM_RTMP_BASE_URL || DEFAULT_RTMP_BASE_URL,
    publicBaseUrl,
    systemctlBin: values.get('systemctl-bin') || env.SYSTEMCTL_BIN || 'systemctl',
    dryRun: values.has('dry-run') || env.RESTREAM_DRY_RUN === 'true',
    noSystemd: values.has('no-systemd') || env.RESTREAM_NO_SYSTEMD === 'true',
  };
}

function inferPublicBaseUrl(apiUrl) {
  try {
    const url = new URL(apiUrl);
    url.pathname = '/live';
    url.search = '';
    return url.toString().replace(/\/+$/, '');
  } catch {
    return 'https://hls.livekinglive.win/live';
  }
}

function configChanged(next, current) {
  return next.donorHash !== current.donorHash || next.outputUrl !== current.outputUrl || next.isActive !== current.isActive;
}

function normalizeSlug(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function isHttpUrl(value) {
  try {
    const url = new URL(String(value || ''));
    return url.protocol === 'http:' || url.protocol === 'https:';
  } catch {
    return false;
  }
}

function shellQuote(value) {
  return `'${String(value).replace(/'/g, "'\\''")}'`;
}

function hashText(value) {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

const currentFile = fileURLToPath(import.meta.url);
if (process.argv[1] === currentFile) {
  main().catch((error) => {
    console.error(error.message || error);
    process.exitCode = 1;
  });
}
