#!/usr/bin/env node
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const DEFAULT_CONFIG_DIR = '/etc/kinglive/restreams';
const DEFAULT_STATE_FILE = '/var/lib/kinglive-restream-sync/state.json';
const DEFAULT_SYSTEMD_PREFIX = 'kinglive-restream@';
const DEFAULT_RTMP_BASE_URL = 'rtmp://127.0.0.1:1935/live';
const DEFAULT_OVERLAY_DIR = '/opt/kinglive/overlays';

async function main() {
  const options = parseArgs(process.argv.slice(2), process.env);
  if (!options.apiUrl) throw new Error('RESTREAM_API_URL is required');
  if (!options.token) throw new Error('RESTREAM_SYNC_TOKEN is required');

  const overlayActions = await syncOverlayAssets(options);
  const desired = await fetchDesiredRestreams(options);
  const state = await readJsonFile(options.stateFile, { managed: {} });
  const actions = await applyDesiredState(desired, state, options);
  await writeJsonFile(options.stateFile, state);

  for (const action of [...overlayActions, ...actions]) {
    console.log(action);
  }
}

export async function applyDesiredState(restreams, state, options) {
  const desired = new Map();
  const actions = [];
  state.managed ||= {};

  for (const restream of restreams) {
    const item = normalizeRestream(restream, options);
    if (!item) continue;
    await resolvePlaylistChannel(item, options);
    desired.set(item.slug, item);
    await writeEnvFile(item, options);

    const current = state.managed[item.slug] || {};
    const restartChanged = item.restartRequestedAt && item.restartRequestedAt !== current.restartRequestedAt;
    const unit = `${options.systemdPrefix}${item.slug}.service`;

    if (item.desiredState === 'stopped' || item.isActive === false) {
      await systemctl(['disable', '--now', unit], options);
      actions.push(`stopped ${item.slug}`);
    } else if (!current.slug) {
      await systemctl(['enable', '--now', unit], options);
      actions.push(`started ${item.slug}`);
    } else if (restartChanged || configChanged(item, current)) {
      await systemctl(['restart', unit], options);
      actions.push(`restarted ${item.slug}`);
    } else {
      actions.push(`kept ${item.slug}`);
    }

    state.managed[item.slug] = {
      slug: item.slug,
      matchId: item.matchId,
      desiredState: item.desiredState,
      isActive: item.isActive,
      donorHash: item.donorHash,
      outputUrl: item.outputUrl,
      channelName: item.channelName,
      transcodeProfile: item.transcodeProfile,
      overlayKey: item.overlayKey,
      resolvedChannelTitle: item.resolvedChannelTitle || '',
      restartRequestedAt: item.restartRequestedAt,
      updatedAt: new Date().toISOString(),
    };
  }

  for (const slug of Object.keys(state.managed)) {
    if (desired.has(slug)) continue;
    const unit = `${options.systemdPrefix}${slug}.service`;
    await systemctl(['disable', '--now', unit], options);
    actions.push(`removed ${slug}`);
    delete state.managed[slug];
  }

  for (const slug of await listManagedSystemdSlugs(options)) {
    if (desired.has(slug)) continue;
    const unit = `${options.systemdPrefix}${slug}.service`;
    await systemctl(['disable', '--now', unit], options);
    actions.push(`removed stale ${slug}`);
    delete state.managed[slug];
  }

  return actions;
}

export function normalizeRestream(restream, options) {
  const slug = normalizeSlug(restream?.slug || restream?.id);
  const donorUrl = String(restream?.donor_url || '').trim();
  const matchId = Number(restream?.match_id);
  if (!slug || !isHttpUrl(donorUrl) || !Number.isFinite(matchId) || matchId <= 0) return null;

  const desiredState = String(restream?.desired_state || 'running').toLowerCase() === 'stopped' ? 'stopped' : 'running';
  const outputUrl = String(restream?.output_url || `${options.publicBaseUrl}/${slug}/index.m3u8`).trim();
  const item = {
    slug,
    matchId,
    donorUrl,
    donorHash: hashText(donorUrl),
    outputUrl,
    rtmpUrl: `${options.rtmpBaseUrl.replace(/\/+$/, '')}/${slug}`,
    label: String(restream?.label || slug).trim(),
    channelName: String(restream?.channel_name || restream?.channelName || '').trim(),
    transcodeProfile: normalizeTranscodeProfile(restream?.transcode_profile || restream?.transcodeProfile),
    overlays: normalizeOverlays(restream?.overlays || restream?.overlay),
    overlayDir: options.overlayDir || DEFAULT_OVERLAY_DIR,
    resolvedInputUrl: donorUrl,
    desiredState,
    isActive: restream?.is_active !== false,
    restartRequestedAt: String(restream?.restart_requested_at || ''),
  };
  item.overlay = item.overlays[0] || null;
  item.overlayKey = item.overlays.length ? JSON.stringify(item.overlays) : '';
  return item;
}

export function renderEnvFile(item) {
  return [
    '# Generated by kinglive restream sync. Edit the admin panel instead.',
    `RESTREAM_SLUG=${shellQuote(item.slug)}`,
    `RESTREAM_LABEL=${shellQuote(item.label)}`,
    `RESTREAM_MATCH_ID=${shellQuote(String(item.matchId))}`,
    `RESTREAM_INPUT_URL=${shellQuote(item.resolvedInputUrl || item.donorUrl)}`,
    `RESTREAM_DONOR_URL=${shellQuote(item.donorUrl)}`,
    `RESTREAM_CHANNEL_NAME=${shellQuote(item.channelName || '')}`,
    ...(item.transcodeProfile ? [`RESTREAM_TRANSCODE_PROFILE=${shellQuote(item.transcodeProfile)}`] : []),
    ...(item.overlay?.enabled
      ? [
          `RESTREAM_OVERLAY_ENABLED='true'`,
          `RESTREAM_OVERLAY_IMAGE=${shellQuote(item.overlay.image)}`,
          `RESTREAM_OVERLAY_DIR=${shellQuote(item.overlayDir || DEFAULT_OVERLAY_DIR)}`,
          `RESTREAM_OVERLAY_POSITION=${shellQuote(item.overlay.position)}`,
          `RESTREAM_OVERLAY_WIDTH=${shellQuote(String(item.overlay.width))}`,
          ...(Number.isFinite(item.overlay.height) ? [`RESTREAM_OVERLAY_HEIGHT=${shellQuote(String(item.overlay.height))}`] : []),
          `RESTREAM_OVERLAY_MARGIN=${shellQuote(String(item.overlay.margin))}`,
          ...(Number.isFinite(item.overlay.xPercent) ? [`RESTREAM_OVERLAY_X_PERCENT=${shellQuote(String(item.overlay.xPercent))}`] : []),
          ...(Number.isFinite(item.overlay.yPercent) ? [`RESTREAM_OVERLAY_Y_PERCENT=${shellQuote(String(item.overlay.yPercent))}`] : []),
          `RESTREAM_OVERLAY_COUNT=${shellQuote(String(item.overlays.length))}`,
          ...item.overlays.flatMap((overlay, index) => {
            const slot = index + 1;
            return [
              `RESTREAM_OVERLAY_${slot}_IMAGE=${shellQuote(overlay.image)}`,
              `RESTREAM_OVERLAY_${slot}_POSITION=${shellQuote(overlay.position)}`,
              `RESTREAM_OVERLAY_${slot}_WIDTH=${shellQuote(String(overlay.width))}`,
              ...(Number.isFinite(overlay.height) ? [`RESTREAM_OVERLAY_${slot}_HEIGHT=${shellQuote(String(overlay.height))}`] : []),
              `RESTREAM_OVERLAY_${slot}_MARGIN=${shellQuote(String(overlay.margin))}`,
              ...(Number.isFinite(overlay.xPercent) ? [`RESTREAM_OVERLAY_${slot}_X_PERCENT=${shellQuote(String(overlay.xPercent))}`] : []),
              ...(Number.isFinite(overlay.yPercent) ? [`RESTREAM_OVERLAY_${slot}_Y_PERCENT=${shellQuote(String(overlay.yPercent))}`] : []),
            ];
          }),
        ]
      : []),
    `RESTREAM_RTMP_URL=${shellQuote(item.rtmpUrl)}`,
    `RESTREAM_PUBLIC_URL=${shellQuote(item.outputUrl)}`,
    '',
  ].join('\n');
}

async function fetchDesiredRestreams(options) {
  const response = await fetch(options.apiUrl, {
    headers: {
      Accept: 'application/json',
      Authorization: `Bearer ${options.token}`,
    },
  });
  if (!response.ok) {
    throw new Error(`restream API failed: ${response.status}`);
  }
  const payload = await response.json();
  return Array.isArray(payload?.restreams) ? payload.restreams : [];
}

export async function syncOverlayAssets(options) {
  if (!options.overlayApiUrl) return [];
  let payload;
  try {
    const response = await fetch(options.overlayApiUrl, {
      headers: {
        Accept: 'application/json',
        Authorization: `Bearer ${options.token}`,
      },
    });
    if (response.status === 404) return [];
    if (!response.ok) throw new Error(`overlay API failed: ${response.status}`);
    payload = await response.json();
  } catch (error) {
    if (options.verbose) console.warn(error.message || error);
    return [];
  }

  const overlays = Array.isArray(payload?.overlays) ? payload.overlays : [];
  const actions = [];
  for (const overlay of overlays) {
    const item = normalizeOverlayAsset(overlay);
    if (!item) continue;
    const changed = await writeOverlayAssetFile(item, options);
    if (changed) actions.push(`synced overlay ${item.id}`);
  }
  return actions;
}

function normalizeOverlayAsset(value = {}) {
  const id = normalizeOverlayImage(value.id);
  const dataBase64 = String(value.data_base64 || value.dataBase64 || '').trim();
  if (!id || !isCustomOverlayImage(id) || !dataBase64) return null;
  if (!looksLikePngBase64(dataBase64)) return null;
  return {
    id,
    data: Buffer.from(dataBase64, 'base64'),
  };
}

async function writeOverlayAssetFile(item, options) {
  const path = join(options.overlayDir, item.id);
  let current = null;
  try {
    current = await readFile(path);
  } catch {}
  if (current && current.equals(item.data)) return false;
  if (options.dryRun) return false;
  await mkdir(dirname(path), { recursive: true, mode: 0o755 });
  const tmp = `${path}.tmp-${process.pid}`;
  await writeFile(tmp, item.data, { mode: 0o644 });
  await rename(tmp, path);
  return true;
}

export async function resolvePlaylistChannel(item, options = {}) {
  if (!item.channelName) return item;
  const response = await fetch(item.donorUrl, {
    headers: { Accept: 'application/vnd.apple.mpegurl, application/x-mpegurl, audio/mpegurl, */*' },
  });
  if (!response.ok) {
    throw new Error(`playlist fetch failed for ${item.slug}: ${response.status}`);
  }
  const text = await response.text();
  const channel = findPlaylistChannel(text, item.channelName, item.donorUrl);
  if (!channel) {
    throw new Error(`channel not found for ${item.slug}: ${item.channelName}`);
  }
  item.resolvedInputUrl = channel.url;
  item.resolvedChannelTitle = channel.title;
  item.resolvedChannelAt = new Date().toISOString();
  if (options.verbose) console.log(`resolved ${item.slug}: ${channel.title}`);
  return item;
}

export function findPlaylistChannel(text, channelName, playlistUrl) {
  const needle = normalizeSearchText(channelName);
  if (!needle) return null;
  const lines = String(text || '').split(/\r?\n/);
  let pending = null;
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;
    if (line.startsWith('#EXTINF')) {
      pending = {
        title: parseExtinfTitle(line),
        tvgName: parseExtinfAttribute(line, 'tvg-name'),
        raw: line,
      };
      continue;
    }
    if (line.startsWith('#')) continue;
    if (!pending) continue;
    const haystack = normalizeSearchText(`${pending.title} ${pending.tvgName} ${pending.raw}`);
    if (haystack.includes(needle)) {
      return {
        title: pending.title || pending.tvgName || channelName,
        url: new URL(line, playlistUrl).toString(),
      };
    }
    pending = null;
  }
  return null;
}

function parseExtinfTitle(line) {
  const commaIndex = line.lastIndexOf(',');
  return commaIndex >= 0 ? line.slice(commaIndex + 1).trim() : '';
}

function parseExtinfAttribute(line, name) {
  const match = line.match(new RegExp(`${name}="([^"]*)"`, 'i'));
  return match?.[1]?.trim() || '';
}

async function writeEnvFile(item, options) {
  const path = join(options.configDir, `${item.slug}.env`);
  const next = renderEnvFile(item);
  let current = '';
  try {
    current = await readFile(path, 'utf8');
  } catch {}
  if (current === next) return;
  if (options.dryRun) return;
  await mkdir(dirname(path), { recursive: true, mode: 0o750 });
  const tmp = `${path}.tmp-${process.pid}`;
  await writeFile(tmp, next, { mode: 0o640 });
  await rename(tmp, path);
}

async function systemctl(args, options) {
  if (options.dryRun) return;
  if (options.noSystemd) return;
  await execFile(options.systemctlBin, args);
}

async function listManagedSystemdSlugs(options) {
  if (options.dryRun || options.noSystemd) return [];
  const output = await execFileOutput(options.systemctlBin, [
    'list-units',
    `${options.systemdPrefix}*.service`,
    '--all',
    '--no-legend',
    '--plain',
  ]).catch(() => '');
  const prefix = options.systemdPrefix;
  return output
    .split(/\r?\n/)
    .map((line) => line.trim().split(/\s+/)[0] || '')
    .filter((unit) => unit.startsWith(prefix) && unit.endsWith('.service'))
    .map((unit) => unit.slice(prefix.length, -'.service'.length))
    .filter(Boolean);
}

async function execFile(command, args) {
  await new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
    });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${command} ${args.join(' ')} failed: ${stderr.trim()}`));
    });
  });
}

async function execFileOutput(command, args) {
  return await new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
    });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve(stdout);
      else reject(new Error(`${command} ${args.join(' ')} failed: ${stderr.trim()}`));
    });
  });
}

async function readJsonFile(path, fallback) {
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch {
    return fallback;
  }
}

async function writeJsonFile(path, value) {
  await mkdir(dirname(path), { recursive: true, mode: 0o750 });
  const tmp = `${path}.tmp-${process.pid}`;
  await writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o640 });
  await rename(tmp, path);
}

function parseArgs(args, env) {
  const values = new Map();
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (!arg.startsWith('--')) continue;
    const key = arg.slice(2);
    const next = args[index + 1];
    if (next && !next.startsWith('--')) {
      values.set(key, next);
      index += 1;
    } else {
      values.set(key, 'true');
    }
  }

  const apiUrl = values.get('api-url') || env.RESTREAM_API_URL || '';
  const overlayApiUrl = values.get('overlay-api-url') || env.RESTREAM_OVERLAY_API_URL || inferOverlayApiUrl(apiUrl);
  const publicBaseUrl = values.get('public-base-url') || env.RESTREAM_PUBLIC_BASE_URL || inferPublicBaseUrl(apiUrl);
  return {
    apiUrl,
    overlayApiUrl,
    token: values.get('token') || env.RESTREAM_SYNC_TOKEN || '',
    configDir: values.get('config-dir') || env.RESTREAM_CONFIG_DIR || DEFAULT_CONFIG_DIR,
    stateFile: values.get('state-file') || env.RESTREAM_STATE_FILE || DEFAULT_STATE_FILE,
    systemdPrefix: values.get('systemd-prefix') || env.RESTREAM_SYSTEMD_PREFIX || DEFAULT_SYSTEMD_PREFIX,
    rtmpBaseUrl: values.get('rtmp-base-url') || env.RESTREAM_RTMP_BASE_URL || DEFAULT_RTMP_BASE_URL,
    overlayDir: values.get('overlay-dir') || env.RESTREAM_OVERLAY_DIR || DEFAULT_OVERLAY_DIR,
    publicBaseUrl,
    systemctlBin: values.get('systemctl-bin') || env.SYSTEMCTL_BIN || 'systemctl',
    dryRun: values.has('dry-run') || env.RESTREAM_DRY_RUN === 'true',
    noSystemd: values.has('no-systemd') || env.RESTREAM_NO_SYSTEMD === 'true',
  };
}

function inferOverlayApiUrl(apiUrl) {
  try {
    const url = new URL(apiUrl);
    url.pathname = '/api/restream-overlays';
    url.search = '';
    return url.toString();
  } catch {
    return '';
  }
}

function inferPublicBaseUrl(apiUrl) {
  try {
    const url = new URL(apiUrl);
    url.pathname = '/live';
    url.search = '';
    return url.toString().replace(/\/+$/, '');
  } catch {
    return 'https://hls.livekinglive.win/live';
  }
}

function configChanged(next, current) {
  return next.donorHash !== current.donorHash
    || next.outputUrl !== current.outputUrl
    || next.isActive !== current.isActive
    || next.channelName !== current.channelName
    || next.transcodeProfile !== current.transcodeProfile
    || next.overlayKey !== current.overlayKey;
}

function normalizeTranscodeProfile(value) {
  const profile = String(value || '').trim();
  return ['auto', 'h264_720p25', 'h264_1080p25', 'h264_1080p50'].includes(profile) ? profile : '';
}

function normalizeSlug(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function normalizeOverlay(value) {
  if (!value || typeof value !== 'object') return null;
  const enabled = value.enabled === true || String(value.enabled || '').toLowerCase() === 'true';
  if (!enabled) return null;
  const image = normalizeOverlayImage(value.image);
  if (!image) return null;
  return {
    enabled: true,
    image,
    position: normalizeOverlayPosition(value.position),
    width: clampInteger(value.width, 80, 1000, 420),
    ...(clampOptionalInteger(value.height, 20, 1000) !== null
      ? { height: clampOptionalInteger(value.height, 20, 1000) }
      : {}),
    margin: clampInteger(value.margin, 0, 200, 24),
    ...(clampOptionalInteger(value.x_percent ?? value.xPercent, 0, 100) !== null
      ? { xPercent: clampOptionalInteger(value.x_percent ?? value.xPercent, 0, 100) }
      : {}),
    ...(clampOptionalInteger(value.y_percent ?? value.yPercent, 0, 100) !== null
      ? { yPercent: clampOptionalInteger(value.y_percent ?? value.yPercent, 0, 100) }
      : {}),
  };
}

function normalizeOverlays(value) {
  const list = Array.isArray(value) ? value : [value];
  const overlays = [];
  for (const entry of list) {
    const overlay = normalizeOverlay(entry);
    if (overlay) overlays.push(overlay);
    if (overlays.length >= 3) break;
  }
  return overlays;
}

function normalizeOverlayImage(value) {
  const image = String(value || '').trim();
  const allowed = new Set([
    'kinglive_player_leaderboard.png',
    'kinglive_banner_1554x192_fixed.png',
    'kinglive_top_banner_1554x192.png',
    'melbet_top_banner_1554x192.png',
    'melbet_banner_1870x245_safe_player.png',
  ]);
  return allowed.has(image) || isCustomOverlayImage(image) ? image : '';
}

function isCustomOverlayImage(value) {
  return /^custom-[a-z0-9][a-z0-9-]{0,70}\.png$/.test(String(value || ''));
}

function looksLikePngBase64(value) {
  try {
    const bytes = Buffer.from(String(value || '').slice(0, 16), 'base64');
    return bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47;
  } catch {
    return false;
  }
}

function normalizeOverlayPosition(value) {
  const position = String(value || '').trim();
  return [
    'top-left',
    'top-center',
    'top-right',
    'center',
    'bottom-left',
    'bottom-center',
    'bottom-right',
  ].includes(position)
    ? position
    : 'top-right';
}

function clampInteger(value, min, max, fallback) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.min(max, Math.max(min, Math.round(number)));
}

function clampOptionalInteger(value, min, max) {
  if (value === null || value === undefined || value === '') return null;
  const number = Number(value);
  if (!Number.isFinite(number)) return null;
  return Math.min(max, Math.max(min, Math.round(number)));
}

function isHttpUrl(value) {
  try {
    const url = new URL(String(value || ''));
    return url.protocol === 'http:' || url.protocol === 'https:';
  } catch {
    return false;
  }
}

function shellQuote(value) {
  return `'${String(value).replace(/'/g, "'\\''")}'`;
}

function normalizeSearchText(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');
}

function hashText(value) {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

const currentFile = fileURLToPath(import.meta.url);
if (process.argv[1] === currentFile) {
  main().catch((error) => {
    console.error(error.message || error);
    process.exitCode = 1;
  });
}
